 GunShopRekrutierenBLUFOR1 enableAI 'MOVE';//aktiv
 GunShopRekrutierenBLUFOR2 enableAI 'MOVE';//aktiv
 GunShopRekrutierenBLUFOR3 enableAI 'MOVE';//aktiv
 GunShopRekrutierenBLUFOR4 enableAI 'MOVE';//aktiv
 GunShopRekrutierenBLUFOR5 enableAI 'MOVE';//inaktiv 
 GunShopRekrutierenBLUFOR6 enableAI 'MOVE';//inaktiv  
 GunShopRekrutierenBLUFOR7 enableAI 'MOVE';//inaktiv 
 GunShopRekrutierenBLUFOR8 enableAI 'MOVE';//inaktiv 
 GunShopRekrutierenBLUFOR9 enableAI 'MOVE';//inaktiv 
 GunShopRekrutierenBLUFOR10 enableAI 'MOVE';//inaktiv